language: kotlin
script:
  - mvn clean verify
after_success:
  - bash <(curl -s https://codecov.io/bash)
env:
  global:
    secure: WgSIs3x+pMQ6L7PZ5AE69WcauE/LmwTt1sxr40q0t3aVZfR+1Martj8wbAbePlgAj4LFe1J2Epe7FZrbgMcHbVwVUGVDvOUYRutUWsXCyfgKmjzeHcVuu8Ii0wZmA4paQAYHtFkdsEGM1F6fxO7MLjZGb3A/GaYLCsXSW1USOpRaGQtWrx/6dM56xQvXAQIflABVZGWAmW6332i8CjVk06//fSmUUJYnoW3viDu1+SuS8yo061zLXaTYd+udDl4SM3alwWFvS/ey2TxaDM7Khgv101tCSWVwj6C52ZU/pa38r2YxvYmHo0cA+AAHXZ2lAMFQvp27pc2yuYndp1gaAOinSsJvbB8071am9nyS/qdxNTqBOcJm2WonNhslGsZxBI9ixULp8x2SPY8AziZ6HngJNr7dn+OkAwy068KMViYd0elxAXlAeO4IHkbUZEp1njK2rLMABG1sgKR4eqlkrEQBsloVvtbB3xO6vQIxTqSHA6x/QpNTmQx+XFQRD154F8JiEn5w58vJmaUF2eTtyS1vJi0NVLGJx54wS3Fc9k9iMOKlJhD6q5sTLE3n+LGS4elvdyjaLYhJKnnqzvaVjqzU4cISi3XAGDmzzQPq960qCUfusFIRXkm7DQaMuPU/NvSzaulB/675rdSZEFCqZrM0qGiX265ibUY0C2cePSw=
